### PR TITLE
add multimc pack creation

### PR DESCRIPTION
**Pull request by NikkyAI**
also your current server installer script will fail eventually
the server installer has to be executed on the target machine because it will download the wrong libraries when executed on the wrong OS

### CODE REVIEW

**Comment by canitzp** [comment]
As far as I know, does mc server not depend on any os specific libraries and I also never got problems with it

**Comment by canitzp** [comment]
and why do i need to run the multi mc pack creator everytime again? doesn't the mmc zip include a auto updater for the skcraft pack?

**Comment by NikkyAI** [comment]
you do not have to but i keep finding weird small issues in the code that could lead to failures in edgecases
.. i swear someone is putting them there
you can make this into a seperate bat file that you execute only once.. but please do .. it will contain the new improved feature selection and better selfupdating

**Comment by canitzp** [comment]
I'm closing this, since there is a deploy_mmc.bat now

**Pull request closed without merging**
